// Code generated by hertz generator.

package service

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processaiinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
